apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-service
  template:
    metadata:
      labels:
        app: messaging-service
    spec:
      containers:
        - name: messaging-service
          image: chathura601/counsilor-messaging-service
          ports:
            - containerPort: 5003
          env:
            - name: DB_HOST
              value: "counsellordb.c6veeqyg6rdp.us-east-1.rds.amazonaws.com"
            - name: DB_USER
              value: "admin"
            - name: DB_PASS
              value: "Cha12345678#"
            - name: DB_NAME
              value: "counsellordb"
